ClimbingConnection/ClimbingConnection.WebMVC/Controllers/GymController.cs
using ClimbingCommunity.Models.GymModels;
using ClimbingCommunity.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClimbingConnection.WebMVC.Controllers
{
    public class GymController : Controller
    {
        // access to service layer
        private GymService CreateGymService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new GymService(userId);
            return service;
        }
        // GET: Gym/Index
        [Authorize]
        public ActionResult Index()
        {

            if (!(TempData.Peek("HasProfile") as bool? ?? false))
            {
                TempData["ClimberMessage"] = "Please complete your profile to access Gyms, Climbers, and Routes";
                return RedirectToAction("Create", "Climber");
            }

            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new GymService(userId);
            var model = service.GetAllGyms();
            return View(model);
        }

        // GET: Gym/Create
        [Authorize]
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Gym/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GymCreate model)
        {
            
            if (!ModelState.IsValid) return View(model);

            var service = CreateGymService();

            if (!service.CreateGym(model))
            {
                ModelState.AddModelError("", "Gym could not be created.");
                return View(model);
            }
            TempData["SaveResult"] = "Your Gym was created.";

            return RedirectToAction("Index");
        }

        // GET: Gym/Details/{id}
        [Authorize]
        public ActionResult Details(int id)
        {
            
            var service = CreateGymService();
            var model = service.GetGymById(id);
            TempData["gymid"] = id;
            return View(model);
        }

        // GET: Gym/Edit/{id}
        [Authorize]
        public ActionResult Edit(int id)
        {
            var service = CreateGymService();
            var gym = service.GetGymById(id);
            var model = new GymEdit()
            {
                GymId = id,
                Name = gym.Name,
                Description = gym.Description,
                Location = gym.Location
            };
            return View(model);
        }

        // POST: Gym/Edit/{id}
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, GymEdit model)
        {
            
            if (!ModelState.IsValid) return View(model);

            if (model.GymId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateGymService();

            if (service.UpdateGym(model))
            {
                TempData["SaveResult"] = "Your gym was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your gym could not be updated.");
            return View(model);
        }

        // GET: Gym/Routes/{id}

        // GET: Gym/Sends/{id}
    }
}

ClimbingConnection/ClimbingConnection.WebMVC/Controllers/SendController.cs
using ClimbingCommunity.Models.SendModels;
using ClimbingCommunity.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClimbingConnection.WebMVC.Controllers
{
    public class SendController : Controller
    {

        // access to service layer
        private SendService CreateSendService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SendService(userId);
            return service;
        }

        // GET: Send/Create
        [Authorize]
        public ActionResult Create()
        {
            var service = new RouteService(Guid.Parse(User.Identity.GetUserId()));
            ViewBag.sendRouteList = service.GetAllRoutes();

            return View();
        }

        // POST: Send/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SendCreate model)
        {
            var routeService = new RouteService(Guid.Parse(User.Identity.GetUserId()));
            ViewBag.sendRouteList = routeService.GetAllRoutes();
            if (!ModelState.IsValid) return View(model);

            var service = CreateSendService();
            if (!service.CreateSend(model))
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        // GET: Send/Index
        public ActionResult Index()
        {
            if (!(TempData.Peek("HasProfile") as bool? ?? false))
            {
                TempData["ClimberMessage"] = "Please complete your profile to access Gyms, Climbers, and Routes";
                return RedirectToAction("Create", "Climber");
            }

            var service = CreateSendService();
            var model = service.GetAllSends();
            return View(model);
        }



        // GET: Send/Gym/{id}
        public ActionResult Gym(int id)
        {
            if (!(TempData.Peek("HasProfile") as bool? ?? false))
            {
                TempData["ClimberMessage"] = "Please complete your profile to access Gyms, Climbers, and Routes";
                return RedirectToAction("Create", "Climber");
            }

            var service = CreateSendService();
            var model = service.GetAllSendsByGymId(id);
            return View(model);
        }


        // GET: Send/Climber
        public ActionResult Climber(int id)
        {
            if (!(TempData.Peek("HasProfile") as bool? ?? false))
            {
                TempData["ClimberMessage"] = "Please complete your profile to access Gyms, Climbers, and Routes";
                return RedirectToAction("Create", "Climber");
            }

            var service = CreateSendService();
            var model = service.GetAllSendsByClimberId(id);
            return View(model);
        }


        // GET: Send/Route
        public ActionResult Route(int id)
        {
            if (!(TempData.Peek("HasProfile") as bool? ?? false))
            {
                TempData["ClimberMessage"] = "Please complete your profile to access Gyms, Climbers, and Routes";
                return RedirectToAction("Create", "Climber");
            }

            var service = CreateSendService();
            var model = service.GetAllSendsByRouteId(id);
            return View(model);
        }
    }
}

ClimbingConnection/ClimbingConnection.WebMVC/Views/Gym/Create.cshtml
@model ClimbingCommunity.Models.GymModels.GymCreate

@{
    ViewBag.Title = "Create";
}

<h2 class="display-4 greentext">Create New Gym</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr / class="bg-dark">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-outline-secondary greentext" id="nopadding" />
            @Html.ActionLink("Back to List", "Index", null, htmlAttributes: new { @class = "btn btn-outline-secondary", id = "nopadding" })
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClimbingConnection/ClimbingConnection.WebMVC/Views/Gym/Details.cshtml
@model ClimbingCommunity.Models.GymModels.GymDetail

@{
    ViewBag.Title = "Details";
}

<h2 class="display-3 greentext mb-0">@Model.Name</h2>
<p>  @Html.DisplayFor(model => model.Location)</p>
<hr / class="bg-dark">
<div>
    <p class="" style="font-size: x-large">
        · @Html.DisplayFor(model => model.Description)
    </p>
    <p class="d-inline greentext ml-auto" style="font-size: xx-large">@Html.DisplayFor(model => model.NumberOfRoutes)</p>
    <p class="d-inline" style="font-size: x-large">routes up right now.</p>
</div>

<div class="container d-flex justify-content-around mb-5 mt-3">
    @{ 
        int gymid = (int)TempData.Peek("gymid");
    }


    @Html.ActionLink("Back to Gyms", "Index", null, htmlAttributes: new { @class = "btn btn-outline-secondary mt-4 p-5 rounded-pill", id = "", style="color: whitesmoke; font-size: x-large;" })
    @Html.ActionLink("View Routes", "Gym","Route", new { id=gymid}, htmlAttributes: new { @class = "btn btn-outline-secondary mt-4 greentext p-5 rounded-pill", id = "", style = "border-color: #9FFF1C !important; font-size: x-large;" })
    @Html.ActionLink("View Sends", "Gym", "Send" , new { id=gymid }, htmlAttributes: new { @class = "btn btn-outline-secondary mt-4 greentext p-5 rounded-pill", id = "", style = "border-color: #9FFF1C !important; font-size: x-large;" })



</div>

ClimbingConnection/ClimbingConnection.WebMVC/Views/Gym/Edit.cshtml
@model ClimbingCommunity.Models.GymModels.GymEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Gym</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gym Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GymId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClimbingConnection/ClimbingConnection.WebMVC/Views/Gym/Index.cshtml
@model IEnumerable<ClimbingCommunity.Models.GymModels.GymListItem>

@{
    ViewBag.Title = "Index";
}

<h2 class="greentext display-4">All Gyms</h2>

<p>
    Can't find a gym?    
    @Html.ActionLink("Add a Gym", "Create")
</p>
<table class="table" style="color: whitesmoke;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfRoutes)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td class="greentext">
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfRoutes)
        </td>
        <td>
            
            @Html.ActionLink("View Gym", "Details", new {  id=item.GymId }, htmlAttributes: new { @class="btn btn-outline-secondary", id="nopadding", style="color: whitesmoke;"})
            
        </td>
    </tr>
}

</table>